name: Documentation

on:
  push:
    branches-ignore:
      - coverity_scan
      - run-fuzzer**
      - debug-fuzzer-**
    paths:
      - '.github/workflows/documentation.yml'
      - 'doc/**'
      - 'man/**'
      - 'raddb/**'
      - 'share/**'
  pull_request:
    paths:
      - '.github/workflows/documentation.yml'
      - 'doc/**'
      - 'man/**'
      - 'raddb/**'
      - 'share/**'

jobs:
  build-docs:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
    - uses: actions/checkout@v3

    - name: Install common build dependencies
      run: |
        sudo apt-get install -y --no-install-recommends \
        asciidoctor \
        doxygen \
        graphviz

    - name: Install Antora
      run: |
        sudo npm i -g @antora/cli@2.0 @antora/site-generator-default@2.0;

    - name: Show versions
      run: |
        make --version
        doxygen --version
        asciidoctor --version

    - name: Build doxygen content
      run: |
         cd doc/doxygen;
         doxygen Doxyfile;

    - name: Build Antora docsite
      run: antora site.yml

    - name: Tar output files
      run: tar -czf site.tgz doc/doxygen/html build/docsite

    - name: Store output
      uses: actions/upload-artifact@v3
      with:
        name: compiled-docs
        path: site.tgz
        retention-days: 1

  # Actual deployment to GitHub Pages is only on pushes to the head of the master branch
  deploy-docs:
    if: ( github.repository_owner == 'FreeRADIUS' ) && ( github.ref == 'refs/heads/master' ) && ( github.event_name == 'push' )

    needs:
      - build-docs

    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    # Permissions needed to deploy on GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write

    # Ensure only one job is attempting to update GitHub Pages
    concurrency:
      group: "documentation"
      cancel-in-progress: true

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Retrieve output
      uses: actions/download-artifact@v3
      with:
        name: compiled-docs

    - name: Extract sites
      run: tar -zxf site.tgz

    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: Upload Doxygen content
      uses: actions/upload-pages-artifact@v1
      with:
        path: 'doc/doxygen/html'

    - name: Deploy doxygen content to GitHub pages
      id: deployment
      uses: actions/deploy-pages@v1
